### PR TITLE
Links battery bar to flashlight

### PR DESCRIPTION
**Pull request by Aklaran**

### CODE REVIEW

**Comment by dijour** [comment]
@Aklaran can you resolve the small merge conflict? Then we can merge

**Comment by Aklaran** [comment]
@dijour unfortunately looks like the project file on the branch we just merged is corrupted. Did you guys run into this issue before? @mjkern

**Comment by mjkern** [comment]
The code seems fine, although when I run it I don't see a difference... Is the battery indicator supposed to work now?

**Comment by Aklaran** [comment]
@mjkern The battery indicator now changes depending on the percent charge the flashlight has. Above 66%, it shows 3, above 33% it shows 2, above 0% it shows 1 and at 0% it shows 0.

The first level right now has such low charge decay that it stays 3 the whole time, then the 2nd level has a decay an order of magnitude higher so it drops off to 0 almost immediately.

**Pull request merged**
